### ISSUE TITLE
missing Method Exception in Revogi Smart Power Strip

### ISSUE THREAD

**Issue by ske5074** [zzarbi/smartthings#6]
Getting the error: error groovy.lang.MissingMethodException: No signature of method: static java.lang.Float.parseFloat() is applicable for argument types: (java.lang.Integer) values: [25212]
Possible solutions: parseFloat(java.lang.String) @ line 119 

The line is:
                    'power': Float.parseFloat(json.data."watt"[i])

My groovy programming sucks and I'm sure it's something basic but if you have any idea on how to resolve the problem I would love to be able to use this code.  Well done by the way!

My Hub details just for reference:

Status | ACTIVE
Firmware Version | 000.017.00012
Hardware Version | hub v2, US customer Rev E

**Comment by zzarbi** [comment]
@wijgalt I added a fixed.. not sure it will work since i don't have this device setup anymore.
The error is that at some point, it use to return a string but it seems that now it's returning a integer which need to be casted into a float .

**Comment by ske5074** [comment]
It looks like it works! Thank you!

I am getting another error now - hopefully this will be simple as well. 

java.lang.NullPointerException: Cannot invoke method getLatestStateFor() on null object @ line 160 

The Code I  see is:
       if(data.status == 1 && aSwitch.currentValue("switch")!='on'){


I really appreciate the help!

**Comment by zzarbi** [comment]
@wijgalt That seems a bit more complicated.. but I think it has something to do with the setup.  Delete the app/devices and re add them. I think the switches may have not been installed properly.

**Comment by ske5074** [comment]
After a complete reinstall of the Device Handlers and the SmartApp code,  it's still throwing the errors.  After installation, I clicked on "Turn off" on switch one and the following errors are logged:

Switch 1 ends in fbbb
Power Strip ends in 4af83 
The RevogiConnect App ends in f2b4 

32a02e8f-4e5d-472c-a179-e8ae8ae4af83 ‎9‎:‎47‎:‎01‎ ‎AM: error java.lang.NullPointerException: Cannot invoke method getLatestStateFor() on null object @ line 160 
9b7bba20-54d5-4f3f-aa99-75f143cff2b4 ‎9‎:‎47‎:‎00‎ ‎AM: debug getChildDevices(false), children=7 
8a8f593b-9c0a-4694-b89c-fdde538cfbbb ‎9‎:‎47‎:‎00‎ ‎AM: error java.lang.NullPointerException: Cannot invoke method findDTOById() on null object 
8a8f593b-9c0a-4694-b89c-fdde538cfbbb ‎9‎:‎46‎:‎49‎ ‎AM: error java.lang.NullPointerException: Cannot invoke method findDTOById() on null object @ line 89 

I'm already weak in Java let alone Groovy - but the findDTOById function I can't even find for reference. If you have any recommendations or advice on troubleshooting I would appreciate it.  I'm still confused as to why the debug() functions aren't being logged in smartthings.  Frustrating.

**Comment by ske5074** [comment]
So I figured out log.debug (I know, I have a long way to go lol) and managed to get this detail out...

Slowly but surely... 

32a02e8f-4e5d-472c-a179-e8ae8ae4af83  7:41:01 PM: error java.lang.IllegalArgumentException: Command 'currentvalue' is not supported by device 8a8f593b-9c0a-4694-b89c-fdde538cfbbb of type 'Revogi Smart Power Strip Switch'. Supported commands: [on, off, refresh, setValue] @ line 161
32a02e8f-4e5d-472c-a179-e8ae8ae4af83  7:41:01 PM: debug data.status=1
32a02e8f-4e5d-472c-a179-e8ae8ae4af83  7:40:04 PM: error java.lang.IllegalArgumentException: Command 'currentvalue' is not supported by device 8a8f593b-9c0a-4694-b89c-fdde538cfbbb of type 'Revogi Smart Power Strip Switch'. Supported commands: [on, off, refresh, setValue] @ line 161
32a02e8f-4e5d-472c-a179-e8ae8ae4af83  7:40:04 PM: debug data.status=1
32a02e8f-4e5d-472c-a179-e8ae8ae4af83  7:39:01 PM: error java.lang.IllegalArgumentException: Command 'currentvalue' is not supported by device 8a8f593b-9c0a-4694-b89c-fdde538cfbbb of type 'Revogi Smart Power Strip Switch'. Supported commands: [on, off, refresh, setValue] @ line 161
32a02e8f-4e5d-472c-a179-e8ae8ae4af83  7:39:01 PM: debug data.status=1

**Comment by zzarbi** [comment]
@wijgalt I remember having some issue with Smartthings when I was working on this. Basically my code is trying to get the current value of the switch (https://github.com/zzarbi/smartthings/blob/master/devicetypes/zzarbi/revogi-smart-power-strip.src/revogi-smart-power-strip.groovy#L160) and it's nor working.

I'm guessing smartthings updated it's API and you would need to find the new way to get the current value of a device
