### ISSUE TITLE
Revogi smart strip

### ISSUE THREAD

**Issue by Nickduino** [zzarbi/smartthings#7]
I know it's a long shot but...

I just received a Revogi smart strip (the SOW323, French plugs) and it seems to work (i.e. it connects to my WiFi) but the app never see it. I was wondering if anyone here could give me a hand or point me to a forum?
Like "you've got to do this SSH wizardry to get it to work" or whatever.

**Comment by zzarbi** [comment]
When you say app, do you meant the smartthings app? My code was only tested with SOW321.

**Comment by Nickduino** [comment]
Non Nicolas ;-)

I can't set it up with the original app from Revogi. I connect to its WiFi network, give it my home network credentials and the strip does connect (I see it on my router's configuration page, it's fot an IP address).
...but Revogi's app never sees it on the network.

**Comment by zzarbi** [comment]
Got it! Yeah not much I can do for you. I bought another smart strip because this one was poorly built and would stop working randomly or disconnect from wifi :/
This repo is for integrating it with SmartThings, I did some reverse engineering to get some commands:
- 192.168.xx.xx/?cmd=511 -> get some status i think
- 192.168.xx.xx/?cmd=200&json={"port":0,"state":1} -> Turn everything on
- 192.168.xx.xx/?cmd=200&json={"port”:1,”state":1} -> Turn the switch 1 on

I would contact their support..

**Comment by Nickduino** [comment]
Well, that's pretty helpful already, I means my strip is properly registered on the network!

**Comment by Nickduino** [comment]
By the way, this version feels pretty solid and nicely built.

Le 30 janv. 2018 01:19, "Nicolas Cerveaux" <notifications@github.com> a
écrit :

Got it! Yeah not much I can do for you. I bought another smart strip
because this one was poorly built and would stop working randomly or
disconnect from wifi :/
This repo is for integrating it with SmartThings, I did some reverse
engineering to get some commands:

   - 192.168.xx.xx/?cmd=511 -> get some status i think
   - 192.168.xx.xx/?cmd=200&json={"port":0,"state":1} -> Turn everything on
   - 192.168.xx.xx/?cmd=200&json={"port”:1,”state":1} -> Turn the switch 1
   on

I would contact their support..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zzarbi/smartthings/issues/7#issuecomment-361429003>,
or mute
the thread

**Comment by Nickduino** [comment]
...can I use it with the SmartThings app?
I tried setting it up but it's asking for a code upfront (something about a hub? I have bo hub).
